version: '3.8'
# Colocar o Spongeforge.jar em /data/mods juntamente com os outros mods do forge
# SpongeMods vão em /data/mods/plugins

services:
  minecraft:
    image: itzg/minecraft-server:java8
    ports:
      - "25565:25565"
    volumes:
      - "mc:/pedirmusicasdata"
    environment:
      EULA: "TRUE"
      VERSION: "1.12.2"
      TYPE: "FORGE"
      FORGE_VERSION: "RECOMMENDED"
      CONSOLE: "true"
      ENABLE_RCON: "false"
      #RCON_PASSWORD: "testing"
      #RCON_PORT: 28016
    restart: unless-stopped
  rcon:
    image: itzg/rcon
    ports:
      - "4326:4326"
      - "4327:4327"
    volumes:
      - "rcon:/opt/rcon-web-admin/db"

volumes:
  mc:
  rcon: